### ISSUE TITLE
Could you add an option to keep all style file and fonts files?

### ISSUE THREAD

**Issue by wuxiaoqiang12** [JimmXinu/EpubSplit#17]
Right now, EpubSplit will only keep files in splited single epub file when it think the file is used in the new book. But sometimes it will make mistake, such as one css file reference to another, and using relative path to refrence a font file. Like following:
f1.css
```css
@charset "utf-8";
@import url("f4.css");
p {
    text-align: justify;
    text-indent: 2em;
    line-height: 130%;
    margin: 0.6em 0em;
    font-family: "livory","DK-SONGTI", "方正宋三简体", "方正书宋", "宋体", 明朝;
}

.pretxt {
    font-family: "qfs","DK-FANGSONG",仿宋,"fangsong",serif;
}
```
f2.css
```css
@charset "utf-8";
/*---常用---*/

@font-face {
	font-family:"qfs";
	src:
	url(../Fonts/f632.ttf);
}
```
it will not keep f2.css and f632.ttf file into the new book.
